Changing build_and_test.sh script to include tests for region spannin…
OpenFAM/OpenFAM pull request #118
Opened 2021-02-28 10:37 UTC by gautham-bhat-k

…g and multiple memory server configuration

2021-03-01 02:49 UTC, mashoodk requested changes

2021-03-01 02:49 UTC, mashoodk commented on CMakeLists.txt
> +link_directories(${PROJECT_SOURCE_DIR}/third-party/build/lib64) # third-party libraries
Why is this change necessary ? What is it getting installed in lib64 ?

2021-03-01 02:49 UTC, mashoodk commented on build_and_test.sh
> +
I am thinking if we should keep it as a separate script and not to run always we run build_and_test.sh. 
What do you think @faizan-barmawer.

2021-03-01 02:49 UTC, mashoodk commented on scripts/run_test.py
> +# Check if user has provided any service interface as "rpc" when openfam model is shared_memeoyr
```suggestion
# Check if user has provided any service interface as "rpc" when openfam model is shared_memory
```

2021-03-01 02:49 UTC, mashoodk commented on scripts/run_test.py
> +                + str(memservice_config_doc["libfabric_port"])
Are we providing same libfabric port for all memory servers ?

2021-03-07 06:05 UTC, mashoodk requested changes

2021-03-08 09:54 UTC, BA-Ramya requested changes
for slurm , replace pkill commands as shown:
scancel --quiet -n metadata_server  > /dev/null 2>&1
scancel --quiet -n memory_server  > /dev/null 2>&1
scancel --quiet -n cis_server  > /dev/null 2>&1
This is because many clusters may not allow more than one job to run

2021-03-10 02:28 UTC, mashoodk approved these changes

2021-03-10 07:21 UTC, BA-Ramya approved these changes

2021-03-10 11:34 UTC, merged