Fixed fam_copy unit test fails as per #141
OpenFAM/OpenFAM pull request #143
Opened 2021-09-22 09:19 UTC by rajakrishi

Fixed #141

2021-09-22 09:20 UTC, rajakrishi commented
Tested on verbs provider
srun: job 137817 has been allocated resources
Content of source dataitem : Test message
Copy 0 : Copying first 1 characters
Copy 1 : Copying first 2 characters
Copy 2 : Copying first 3 characters
Copy 3 : Copying first 4 characters
Copy 4 : Copying first 5 characters
Copy 5 : Copying first 6 characters
Copy 6 : Copying first 7 characters
Copy 7 : Copying first 8 characters
Copy 8 : Copying first 9 characters
Copy 9 : Copying first 10 characters
Copy 10 : Copying first 11 characters
Copy 11 : Copying first 12 characters
waiting for Copy : 11
waiting for Copy : 10
waiting for Copy : 9
waiting for Copy : 8
waiting for Copy : 7
waiting for Copy : 6
waiting for Copy : 5
waiting for Copy : 4
waiting for Copy : 3
waiting for Copy : 2
waiting for Copy : 1
waiting for Copy : 0
Copy 0 : T : CORRECT
Copy 1 : Te : CORRECT
Copy 2 : Tes : CORRECT
Copy 3 : Test : CORRECT
Copy 4 : Test  : CORRECT
Copy 5 : Test m : CORRECT
Copy 6 : Test me : CORRECT
Copy 7 : Test mes : CORRECT
Copy 8 : Test mess : CORRECT
Copy 9 : Test messa : CORRECT
Copy 10 : Test messag : CORRECT
Copy 11 : Test message : CORRECT
fam finalize successful
rishi@xxxx3:/nfs/rishi/OpenFAM/build$

2021-09-23 03:46 UTC, mashoodk requested changes
See if we should validate the copy output in "fam_copy_test.cpp". In fam_copy_test.cpp we are comparing the strings (original vs final), but we are not throwing any error.

2021-09-23 03:46 UTC, mashoodk commented on src/cis/fam_cis.h
> +                       uint64_t srcCopyStart, uint64_t srcKey, uint64_t srcBaseAddr,
Please run git-clang-format

2021-09-29 11:01 UTC, rajakrishi commented
> See if we should validate the copy output in "fam_copy_test.cpp". In fam_copy_test.cpp we are comparing the strings (original vs final), but we are not throwing any error.

We can come out of loop with break once we fall in Wrong (aka else scope). No need for further compare string if one string fails. Let me know if that is fine with you or you were suggesting to throw exception if one char does not matches ?

2021-09-29 12:56 UTC, BA-Ramya reviewed
In file src/memory_service/fam_memory_service.h, variable name is srcBaseAdd.
May be we can change that to srcBaseAddr to maintain uniformity.

In file test/unit-test/fam-api/fam_copy_test.cpp 
change MESSAGE_SIZE to NUM_DATAITEMS as the name is misleading.

2021-09-29 15:06 UTC, rajakrishi commented
> In file src/memory_service/fam_memory_service.h, variable name is srcBaseAdd. May be we can change that to srcBaseAddr to maintain uniformity.
> 
> In file test/unit-test/fam-api/fam_copy_test.cpp change MESSAGE_SIZE to NUM_DATAITEMS as the name is misleading.



> In file src/memory_service/fam_memory_service.h, variable name is srcBaseAdd. May be we can change that to srcBaseAddr to maintain uniformity.
> 
> In file test/unit-test/fam-api/fam_copy_test.cpp change MESSAGE_SIZE to NUM_DATAITEMS as the name is misleading.

Thanks Ramya. I have addressed the first input. We should maintain uniformity. I have checked in the code 
For second input, it is not NUM of Data item, it is MESSAGE size only to check and compare.

2021-09-30 16:59 UTC, BA-Ramya approved these changes
Review comments addressed

2021-10-01 05:04 UTC, faizan-barmawer approved these changes
Code changes look good.

Regards,
Faizan

2021-10-01 05:07 UTC, mashoodk approved these changes

2021-10-01 05:11 UTC, merged