Dataitem interleaving
OpenFAM/OpenFAM pull request #156
Opened 2021-10-26 17:37 UTC by gautham-bhat-k

2021-11-05 07:26 UTC, mashoodk requested changes

2021-11-05 07:26 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +		                                    uint64_t offset, uint64_t nbytes) {
Add more comments. Say more explanations for the calculations.

2021-11-05 07:26 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +    uint64_t startOffset = ((offset/interleaveSize) - startIndex)/usedMemsrvCnt;
Do you think renaming this variable will work better - to something like startBlock or currentBlock.

2021-11-05 07:26 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +    if(startIndex > (usedMemsrvCnt - 1)) {
What should happen in this if condition ?

2021-11-08 07:52 UTC, mashoodk requested changes

2021-11-08 07:52 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +		uint64_t currentServerIndex = startIndex;
in the next iteration do run git-clang-format

2021-11-08 07:52 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +		uint64_t currentServerIndex = startIndex;
in the next iteration do run git-clang-format

2021-11-10 16:52 UTC, mashoodk requested changes
Some more comments.

2021-11-10 16:52 UTC, mashoodk commented on src/allocator/fam_allocator_client.cpp
> +    // globalDescriptor.offset = info.offset;
Do we need to enable this code ?

2021-11-10 16:52 UTC, mashoodk commented on src/allocator/fam_allocator_client.cpp
> +    dataItem->set_interleave_size(16384);
Add a #TODO to change this hard-coding.

2021-11-10 16:52 UTC, mashoodk commented on src/common/atomic_queue.cpp
> +                  // ret = fabric_write(
Add TODO

2022-01-17 06:08 UTC, mashoodk requested changes
minor comments.

2022-01-17 06:08 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +     * from the starting posion of any interleave block.
Correct spelling in the comment - "position", "the"

2022-02-10 09:45 UTC, mashoodk requested changes

2022-02-10 09:45 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_dataitem_interleave_test.cpp
> +}
Add couple of atomic tests to operate on different offsets (offsets can be in second stripe)

2022-02-14 09:47 UTC, mashoodk requested changes

2022-02-14 09:47 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +    // Fam_DataItem_Metadata dataitem;
You can remove commented line

2022-02-16 10:24 UTC, mashoodk requested changes

2022-02-17 04:52 UTC, mashoodk requested changes

2022-02-17 14:20 UTC, mashoodk requested changes

2022-02-22 09:06 UTC, soumya-pn reviewed
We can set this to 1GB itself as we mentioned here as 1G is the default value.

2022-02-22 09:13 UTC, soumya-pn commented on config/fam_metadata_config.yaml
> +region_span_size_per_memoryserver: 1048576
We can change this back to 1GB as default mentioned is 1GB.

2022-02-22 09:16 UTC, soumya-pn commented on scripts/run_test.py
> +   if_device: eth1
The changes in this file also can be reverted.

2022-03-16 09:10 UTC, closed without merging