- Added comments fot Fam_Stat and Fam_Backup_Options.
OpenFAM/OpenFAM pull request #164
Opened 2021-12-13 06:17 UTC by BA-Ramya

- Fixed compilation issue with pmi2 unit test case.

2022-02-02 14:39 UTC, mashoodk approved these changes

2022-03-10 11:10 UTC, faizan-barmawer requested changes
We write the test scenario such that we know whether the API is expected to succeed or throw an exception. It is better to use appropriate gtest  EXPECT_* function to report the success/failure of the test scenario. 
Any reg-test failure indicates that either there is a problem with test scenairo, test system configuration or there is implementaion issue. 

Regards,
Faizan

2022-03-18 09:39 UTC, BA-Ramya commented on src/allocator/memserver_allocator.cpp
> +            THROW_ERRNO_MSG(Memory_Service_Exception, BACKUP_DATA_INVALID,
Addressed

2022-03-18 09:42 UTC, BA-Ramya commented on test/reg-test/fam-api-reg/fam_backup_restore_reg_test.cpp
> +        cout << "fam_backup exception: " << e.fam_error_msg() << endl;
For some scenarios, the exception can happen either during fam_backup/fam_backup_wait depending on the way services are configured. For such cases, a flag is being used and set if exceptions occur. This flag value is verified after try catch block to ensure that exception is raised. For rest of scenarios EXPECT_THROW is being used.

2022-03-18 13:44 UTC, mashoodk approved these changes

2022-03-21 11:45 UTC, faizan-barmawer approved these changes
Code changes look good.
I have few minor comments in the code, that can be ignored.

Regards,
Faizan

2022-03-21 11:45 UTC, faizan-barmawer commented on src/common/fam_internal_exception.h
> +    case BACKUP_SIZE_TOO_LONG:
Should we use "LARGE" in place of "LONG" while using it with data item/backup "size" ?
minor comment, you can ignore this.

2022-03-21 11:45 UTC, faizan-barmawer commented on test/reg-test/fam-api-reg/fam_min_max_atomics_mt_reg_test.cpp
> +//#define SHM_CHECK (strcmp(openFamModel, "shared_memory") == 0)
Do you want to leave this line commented or want to delete?

2022-03-22 03:53 UTC, mashoodk approved these changes

2022-03-22 03:54 UTC, merged