Changes done in initialize code path to set the hardware network interface  for PE node and memory servers
OpenFAM/OpenFAM pull request #182
Opened 2022-02-15 10:42 UTC by soumya-pn

Changes done in initialize code path to set the hardware network interface  for PE node and memory servers

2022-02-16 08:11 UTC, mashoodk requested changes

2022-02-16 08:11 UTC, mashoodk commented on config/fam_pe_config.yaml
> +#pe_if_device: ib0
I think you can just give if_device. Also add a comment that it is valid only for verbs provider

2022-02-16 08:11 UTC, mashoodk commented on src/common/fam_ops_libfabric.h
> +    Fam_Ops_Libfabric(bool source, const char *libfabricProvider, const char *if_device,
git-clang-format

2022-02-16 08:11 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +		                     const char *pe_if_device,
I guess this code is common for memory server and pe. You can rename the variable to *if_device or if_device_str.

2022-02-17 01:56 UTC, mashoodk approved these changes

2022-02-17 02:06 UTC, mashoodk requested changes

2022-02-17 02:06 UTC, mashoodk commented on src/common/fam_libfabric.cpp
> +                      char *provider, char *if_device, struct fi_info **fi,
Can you add if_device argument description above.

2022-03-10 16:04 UTC, faizan-barmawer requested changes
Changes look good.
Please rebase your git branch to the latest upstread/devel branch and do one minor change as suggested. 

Regards,
Faizan

2022-03-23 04:35 UTC, faizan-barmawer approved these changes
Code changes look good.

Regards,
Faizan

2022-03-23 04:37 UTC, mashoodk approved these changes

2022-03-23 04:38 UTC, merged