Adding 9 regression tests for fam context modelling
OpenFAM/OpenFAM pull request #188
Opened 2022-03-08 18:38 UTC by cynara-justine

Adding 9 regression tests for fam context modelling
Also added a temporary fix for throwing error in some cases in fam_context.h file to prevent the issue where earlier it was silently proceeding ignoring the error

2022-03-09 05:12 UTC, mashoodk requested changes

2022-03-09 05:12 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_context_reg_test.cpp
> +        EXPECT_NO_THROW(rd= my_fam->fam_create_region(
Can you move this create region outside of the loop

2022-03-09 17:15 UTC, mashoodk requested changes

2022-03-09 17:15 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_context_reg_test.cpp
> +        EXPECT_NO_THROW(my_fam->fam_destroy_region(rd));
This should be outside the loop

2022-03-10 15:39 UTC, faizan-barmawer approved these changes
These test cases look fine.
We can add more test scenario:
1. Cover all I/O APIs - you have covered only atomic APIs, add get/put/scatter/gather blocking and non-blocking
2. Use same context from multiple threads, doing different operations - get, put, progress, etc.
3. Add few negative tests - call control path APIs like allocate/create region from context object. This should throw exception.

You can add more tests in this PR or can raise a new PR, anything is fine.

Regards,
Faizan

2022-03-11 03:31 UTC, cynara-justine commented
Thanks for reviewing.  Please go ahead with merging these changes.  I shall add new test cases and raise a new PR for those.

Thanks and regards,
Cynara

From: Syed Ismail Faizan Barmawer ***@***.***>
Sent: Thursday, March 10, 2022 9:10 PM
To: OpenFAM/OpenFAM ***@***.***>
Cc: Justine, Cynara ***@***.***>; Author ***@***.***>
Subject: Re: [OpenFAM/OpenFAM] Adding 9 regression tests for fam context modelling (PR #188)


@faizan-barmawer approved this pull request.

These test cases look fine.
We can add more test scenario:

  1.  Cover all I/O APIs - you have covered only atomic APIs, add get/put/scatter/gather blocking and non-blocking
  2.  Use same context from multiple threads, doing different operations - get, put, progress, etc.
  3.  Add few negative tests - call control path APIs like allocate/create region from context object. This should throw exception.

You can add more tests in this PR or can raise a new PR, anything is fine.

Regards,
Faizan

—
Reply to this email directly, view it on GitHub<https://github.com/OpenFAM/OpenFAM/pull/188#pullrequestreview-906029742>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWN4234GKETNLLBP3VETAJTU7IJVHANCNFSM5QHFJIKQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-03-11 03:52 UTC, mashoodk requested changes

2022-03-11 03:52 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_context_mt_reg_test.cpp
> +    // We are done with the operations. Destroy the region and everything in it
Can you remove second part of the comment. We are not destroying the region here.

2022-03-11 04:03 UTC, mashoodk approved these changes

2022-03-11 04:04 UTC, merged