Changes in fam_options
OpenFAM/OpenFAM pull request #200
Opened 2022-03-31 11:17 UTC by soumya-pn

2022-03-31 11:23 UTC, mashoodk requested changes

2022-03-31 11:23 UTC, mashoodk commented on include/fam/fam.h
> +    char *fam_default_memory_type;
do add a comment for fam_default_memory_type

2022-03-31 11:23 UTC, mashoodk commented on src/fam-api/fam.cpp
> +        famOptions.if_device = strdup("");
copy paste error ?

2022-03-31 13:14 UTC, mashoodk requested changes

2022-03-31 13:14 UTC, mashoodk commented on src/common/fam_options.h
> +    /** Interface device used in the pe side for communication */
Interface device used by the pe for communication

2022-03-31 14:42 UTC, mashoodk approved these changes

2022-04-01 06:17 UTC, faizan-barmawer approved these changes
Changes look fine.

Regards,
Faizan

2022-04-01 06:25 UTC, merged