Fixed HewlettPackard/gull#30 Changes have been made to NVMM code also…
OpenFAM/OpenFAM pull request #208
Opened 2022-04-18 11:46 UTC by cynara-justine

Fixed https://github.com/HewlettPackard/gull/issues/30 Changes have been made to NVMM code also for fixing this issue. Changes in OpenFAM code include handling the newly added return value for StartNVMM()and addition of conditions to handle exceptions and error scenarios.

2022-04-21 03:15 UTC, mashoodk requested changes

2022-04-21 03:15 UTC, mashoodk commented on src/memory-node/memory_server_main.cpp
> +            message << "Starting of metadata server failed";
message string needs modification : Starting of memory server failed

2022-04-21 03:15 UTC, mashoodk commented on src/common/fam_internal_exception.h
> +    case METADATA_SERVER_START_FAILED:
Can you add METADATA_SERVER_START_FAILED to FAM_ERR_METADATA

2022-04-22 09:13 UTC, mashoodk approved these changes

2022-04-22 10:08 UTC, faizan-barmawer approved these changes
Code changes look fine.

Regards,
Faizan

2022-04-25 16:49 UTC, merged