Fixed #209 and #213 : fam_progress multithreaded tests
OpenFAM/OpenFAM pull request #216
Opened 2022-05-10 10:23 UTC by cynara-justine

Fixed https://github.com/OpenFAM/OpenFAM/issues/209 and  https://github.com/OpenFAM/OpenFAM/issues/213

2022-05-12 04:02 UTC, mashoodk requested changes

2022-05-12 04:02 UTC, mashoodk commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +        ctx[i]->fam_quiet();
Here, we may end up calling fam_quiet from multiple in same context. Do you want to consider changing this logic ?

2022-05-12 04:02 UTC, mashoodk commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +        cout << "Error in barrier initialization" << endl;
extra spacing above this line.

2022-05-12 04:02 UTC, mashoodk commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +    pthread_barrier_destroy(&barrier);
Shouldn't pthread_barrier_destroy be called after pthread_join.

2022-05-12 07:40 UTC, cynara-justine commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +        cout << "Error in barrier initialization" << endl;
Thanks, removed the extra line.

2022-05-12 07:41 UTC, cynara-justine commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +#define NUM_THREADS 32
With 50 iterations, it is completing in less than a second - now fam progress values come around 96, 2 etc. then 0. So the functionality is working and so we decided to proceed.
With 500 iterations, fam_progress values are in the range of 2500.  As it takes a long time, we have set the number of iterations to 50 for the test program that is being checked in

2022-05-13 04:31 UTC, mashoodk requested changes

2022-05-13 04:31 UTC, mashoodk commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +    cpu_set_t cpuset;
You can comment the cpu set affinity code.

2022-05-13 04:31 UTC, mashoodk commented on test/unit-test/fam-api/fam_progress_mt.cpp
> +                    cout << "I/Os in Progress for context" << i << " is "
Instead of printing all the value, you can print maximum value.

2022-05-13 06:08 UTC, faizan-barmawer requested changes
Overall tests look fine.
Few minor changes to handle.

Regards,
Faizan

2022-05-23 07:07 UTC, mashoodk approved these changes

2022-05-23 07:10 UTC, faizan-barmawer approved these changes
Code looks good to merge.

2022-05-23 07:16 UTC, merged