Fixed region name clash issue in the case of multiple PEs
OpenFAM/OpenFAM pull request #225
Opened 2022-06-15 09:39 UTC by cynara-justine

Fixed region name clash issue in the case of multiple PEs

2022-07-07 08:09 UTC, mashoodk requested changes

2022-07-07 08:09 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_context_reg_test.cpp
> +    /*
Please remove commented code

2022-07-07 08:09 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_context_reg_test.cpp
> +    EXPECT_THROW(ctx->fam_initialize(myApplication, &fam_opts), Fam_Exception);
DO we need to change myApplication in fam_initialize

2022-07-08 03:32 UTC, mashoodk approved these changes

2022-07-11 03:06 UTC, mashoodk approved these changes

2022-07-12 08:42 UTC, faizan-barmawer approved these changes
Code changes look fine.

2022-07-12 08:47 UTC, merged