Multi Memory server - additional Metadata interfaces
OpenFAM/OpenFAM pull request #70
Opened 2020-08-13 17:19 UTC by BA-Ramya

2020-08-27 15:25 UTC, gautham-bhat-k requested changes

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_server.cpp
> +
memory server list needs to be returned back ?

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_server.cpp
> +
memory server list has to be returned ?

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
> +}
Use exceptions rather than error code

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
> +}
Use exceptions rather than error code

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/metadata_client_counters.tbl
> +MEMSERVER_COUNTER(client_metadata_validate_and_allocate_dataitem)
Why direct_metadata_validate_and_destroy_region missing?

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/metadata_server_counters.tbl
> +MEMSERVER_COUNTER(server_metadata_validate_and_allocate_dataitem)
Why direct_metadata_validate_and_destroy_region missing?

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_client.cpp
> +}
Use eceptions

2020-08-27 15:25 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_client.cpp
> +}
Use exceptions

2020-08-28 18:34 UTC, gautham-bhat-k requested changes

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>      if (ret != 0) {
```suggestion
    if (ret == 0) {
```

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>          if (ret == 0) {
```suggestion
        if (ret == 1) {
```

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>      if (ret == 0) {
```suggestion
    if (ret == 1) {
```

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>      if (ret != 0) {
```suggestion
    if (ret == 0) {
```

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>      if (ret == 0) {
returning boolean value,

2020-08-28 18:34 UTC, gautham-bhat-k commented on src/metadata/fam_metadata_service_direct.cpp
>      if (ret != 0) {
```suggestion
    if (ret == 0) {
```

2020-09-02 12:40 UTC, BA-Ramya commented on src/metadata/fam_metadata_service_client.cpp
> +}
Addressed

2020-09-03 12:45 UTC, rajakrishi commented
Can one of the admins verify this patch?

2020-09-22 09:01 UTC, mashoodk requested changes

2020-09-22 09:01 UTC, mashoodk commented on src/cis/fam_cis_server.cpp
> +
if there is no change we should remove this file

2020-10-04 16:55 UTC, mashoodk requested changes

2020-10-04 16:55 UTC, mashoodk commented on src/allocator/fam_allocator_client.cpp
>          info = famCIS->allocate(name, nbytes, accessPermissions, regionId,
There is some mess up in spacing in this function. can you correct it ?

2020-10-04 16:55 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +        metadataService->metadata_reset_bitmap(regionId);
In addition to reseting the bitmap, we need to revert back the created region in some memory servers. i.e call destroy region, where ever create_region was successful.

2020-10-04 16:55 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +        if (id == (used_memsrv_cnt - 1)) {
We need to resize each memory server by equal quantity. If there is a remainder it has to be added to all memory servers.

2020-10-04 16:55 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    uint64_t dataitemId = (id * 8388608) + info.offset / MIN_OBJ_SIZE;
Left shift by a constant.

2020-10-04 16:55 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    uint64_t dataitemId = (memoryServerId*8388608) + offset / MIN_OBJ_SIZE;
Left shift by a constant.

2020-10-04 16:55 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    uint64_t dataitemId = (memoryServerId*8388608) + offset / MIN_OBJ_SIZE;
left shift by a constant.

2020-10-04 16:55 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +#define SIZE_PER_MEMSERVER 4096
Can you increase this number. Also we will add this to configuration file. We can take that up in next PR if not in this.

2020-10-04 16:55 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +                       //Check if heap which will be used for storing dataitem metadata KVS
Can you add this to a function ?

2020-10-04 16:55 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +
add this to a function..

2020-10-04 16:55 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +        // Size is smaller than page size and hence using single memory.
SIZE_PER_MEMSERVER

2020-10-04 16:55 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.h
> +#define MIN_HEAP_SIZE (100 * (1UL << 20))
100 MB ? Add a comment what it is.

2020-10-05 06:13 UTC, gautham-bhat-k requested changes

2020-10-05 06:13 UTC, gautham-bhat-k commented on src/metadata_service/fam_metadata_service_direct.cpp
> +        //OPEN_METADATA_KVS(dataitemNameRoot, tmpSize, regionId,
remove commented code

2020-10-05 18:28 UTC, mashoodk requested changes

2020-10-05 18:28 UTC, mashoodk commented on .gitignore
> +src/allocator/.nfs0000001186a6003800000e5e
Not sure if this is needed. "src/allocator/.nfs0000001186a6003800000e5e". Isnt this a temporary file.

2020-10-05 18:28 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +	size_t aligned_size = (size + 64 - 1) & -64;
Use macros and not actual values. Not sure if i completely understood the logic here. We will discuss it tomorrow.

2020-10-05 18:28 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +        	Fam_Memory_Service *memoryService =  memoryServiceList[n];
We might have to wait for this completion.

2020-10-05 18:28 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +//    uint64_t dataitemId = (id << 32) + info.offset / MIN_OBJ_SIZE;
remove commented code.

2020-10-05 18:28 UTC, mashoodk commented on test/reg-test/allocator-reg/fam_resize_reg_test.cpp
> +//        EXPECT_THROW(item2 =
commented code.

2020-10-05 18:28 UTC, mashoodk commented on test/reg-test/allocator-reg/fam_resize_reg_test.cpp
> +        int i = 0;
Not sure if i understood completely.

2020-10-07 05:34 UTC, mashoodk requested changes

2020-10-07 05:34 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    uint64_t srcDataitemId = (memoryServerId << 32) + srcOffset / MIN_OBJ_SIZE;
use get_dataitem_id, BTW is it possible to make get_dataitem_id a macro or inline function.

2020-10-07 05:34 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +inline bool
verify formatting...

2020-10-07 05:34 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +inline void Fam_Metadata_Service_Direct::Impl_::destroy_dataitem_metadata_KVS(
formating..

2020-10-07 05:34 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +        get_regionid_from_bitmap(regionid);
Why are we calling get_regionid_from_bitmap here.

2020-10-07 05:34 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_direct.cpp
> +    // already exists.If exists return error.
Leave a space before If.

2020-10-07 05:34 UTC, mashoodk commented on src/metadata_service/fam_metadata_service_server.cpp
> +::grpc::Status Fam_Metadata_Service_Server::metadata_reset_bitmap(
can you add a line break here.

2020-10-07 05:34 UTC, mashoodk commented on test/reg-test/allocator-reg/fam_resize_reg_test.cpp
> +            EXPECT_NE((void *)NULL, item1);
i think this check is not needed.

2020-10-07 05:34 UTC, mashoodk commented on test/reg-test/allocator-reg/fam_resize_reg_test.cpp
>          EXPECT_NO_THROW(my_fam->fam_deallocate(item1));
You can remove these two deallocate calls.. destroy will deallocate it.

2020-10-08 12:18 UTC, mashoodk requested changes

2020-10-08 12:18 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +inline int  Fam_CIS_Direct::create_region_failure_cleanup(std::vector<int> create_region_success_list, std::vector<Fam_Memory_Service *> memoryServiceList, uint64_t regionId) {
Soft reset all your commits and do git-clang-format

2020-10-08 12:18 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    if (check_dataitem_permission(dataitem, 1, 0, uid, gid)) {
better to use metadataserverId here also. Search for all occurance of check_dataitem_permission.

2020-10-08 12:18 UTC, mashoodk commented on src/cis/fam_cis_direct.cpp
> +    if (check_dataitem_permission(dataitem, 1, 0, uid, gid)) {
better to use metadataserverId

2020-10-08 15:25 UTC, gautham-bhat-k approved these changes

2020-10-08 16:10 UTC, mashoodk approved these changes

2020-10-08 16:11 UTC, merged