Fixing a bug in fam_copy:
OpenFAM/OpenFAM pull request #73
Opened 2020-09-10 15:58 UTC by gautham-bhat-k

fam_copy was not behaving asynchonously in case of CIS direct interface.
It is fixed with this commit.

2020-09-10 16:00 UTC, rajakrishi commented
Can one of the admins verify this patch?

2020-09-14 10:02 UTC, mashoodk requested changes
minor comments..

2020-09-14 10:02 UTC, mashoodk commented on CMakeLists.txt
> +set( TEST_CIS_SERVER "10.93.232.37" )
Remove these changes.

2020-09-21 08:19 UTC, faizan-barmawer approved these changes
Code looks fine.

2020-09-21 08:34 UTC, mashoodk approved these changes

2020-09-21 08:35 UTC, merged