Added regression testcases for multiple memory server
OpenFAM/OpenFAM pull request #75
Opened 2020-09-15 09:52 UTC by rajakrishi

Added testcases for these API:
  - Create Region
  - Destroy region
  - Resize
  - Permission Check (For dataitem & Region)

2020-09-15 09:55 UTC, rajakrishi commented
Can one of the admins verify this patch?

2020-09-15 10:58 UTC, mashoodk requested changes

2020-09-15 10:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + * Copyright (c) 2019 Hewlett Packard Enterprise Development, LP. All rights
Update copyright to 2020

2020-09-15 10:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +#if !defined(SHM) && defined(MEMSERVER_PROFILE)
This #ifdef is not needed i think. Is this there in other regression tests ?

2020-09-15 10:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +       NUM_MM_ITERATIONS = atoi(argv[1]);
What is the default value of NUM_MM_ITERATIONS

2020-09-15 10:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +    }
if we are passing command line to regression test, we will need to update cmake file with args. Also we need to supply default values..

2020-09-20 03:58 UTC, mashoodk requested changes

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + * fam_copy_reg_test.cpp
File name in comment is wrong..

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +#include "cis/fam_cis_client.h"
You can remove this header file.

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +TEST(FamDataPath, CreateDestroyRegion) {
This is not FamDataPath. May be you can name it as FamControlPath

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/CMakeLists.txt
> +elseif(${TEST_RUNTIME} STREQUAL "PMIX")
Shouldnt have these changes.

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +#define RESIZE_REGION_SIZE 1048576
keep RESIZE_REGION_SIZE as same as BIG_REGION_SIZE

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + // EXPECT_NO_THROW(rpc->generate_profile());
remove commented lines..

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + for (int i = 0; i < NUM_MM_ITERATIONS; i++) {
I think we need to rethink this resize in a loop logic - We do not need to resize NUM_MM_ITERATIONS times. Couple of iterations should be enough

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + for (int i = 0; i < NUM_MM_ITERATIONS; i++) {
We shouldnt change permission for lots of iterations. We can allocate many dataitems and change its permission.
Basically this loop can be for allocate - and then change permission. 

Say 
for (int i = 0; i < NUM_MM_ITERATIONS; i++) {
allocate()
change_permission()
 }

2020-09-20 03:58 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> + for (int i = 0; i < NUM_MM_ITERATIONS; i++) {
Same here - The loop around change permission in microbenchmark was to take performance measurement. We do not need that loop here.

2020-09-23 04:34 UTC, mashoodk requested changes

2020-09-23 04:34 UTC, mashoodk commented on test/microbench/fam-api-mb/fam_microbenchmark_allocator.cpp
> +         EXPECT_NO_THROW(descLocal = my_fam->fam_lookup_region(testRegionLocal));
i think you will need to remove EXPECT_NO_THROW around fam_lookup_region, test case will fail - seeing an expect no throw and try catch around is not useful.

2020-09-23 04:34 UTC, mashoodk commented on test/microbench/fam-api-mb/fam_microbenchmark_allocator.cpp
> +        //cout << "fam region failed" << endl;
you can remove this line

2020-09-23 04:34 UTC, mashoodk commented on test/reg-test/fam-api-reg/fam_control_path_reg_test.cpp
> +//#define MESSAGE_SIZE 12
remove commented code.

2020-09-29 09:31 UTC, mashoodk approved these changes

2020-09-29 09:33 UTC, merged