ATL scatter gather functionality added
OpenFAM/OpenFAM pull request #80
Opened 2020-09-28 13:30 UTC by chinmay-ghosh

2020-10-05 07:14 UTC, mashoodk requested changes

2020-10-05 07:14 UTC, mashoodk commented on src/common/atomic_queue.cpp
> +                        allocator->deallocate(ATOMIC_REGION_ID,
Can this deallocate error be ignored? We might have completed deallocated, But ATOMIC_BUFFER_ALLOCATED might be still set.

2020-10-07 02:43 UTC, faizan-barmawer requested changes

2020-10-07 02:43 UTC, faizan-barmawer commented on src/cis/fam_cis_rpc.proto
> +    uint64 indexsize = 6;
Is this indexsize or elementsize?

2020-10-07 02:43 UTC, faizan-barmawer commented on src/common/atomic_queue.cpp
> +uint64_t *parseIndex(char *inpStr, uint64_t nElements) {
Yes, It better to go with "repeated" rpc interface type to send across the element index array.

2020-10-07 02:43 UTC, faizan-barmawer commented on src/common/atomic_queue.cpp
> +                                openfam_persist(localPointerB, bufferSize);
You can combine try-catch for all openfam_persist calls, unless you want to perform some cleanup operation for any of these call failures.

2020-10-07 02:43 UTC, faizan-barmawer commented on src/memory_service/fam_memory_service_direct.cpp
> +    int ret = atomicQ[qId].push(&InpMsg, elementIndex);
"elementIndex" is a local string pointer, coming from rpc request parameter. 
In the "push" function, hope we are copying the content of this string and not saving the string pointer.

Looks like you are doing this operation at line# 177-184 atomic_queue.cpp

2020-10-11 16:31 UTC, mashoodk approved these changes

2020-10-15 06:51 UTC, faizan-barmawer approved these changes
Code looks good to merge.

Regards,
Faizan

2020-10-15 11:38 UTC, merged