fam_copy data items across memory server
OpenFAM/OpenFAM pull request #84
Opened 2020-10-19 09:45 UTC by faizan-barmawer

fam_copy between data item from different memory server to be performed from destination memory server.

2020-10-21 09:18 UTC, faizan-barmawer commented
Updated the PR with all the changes.
- Removed commented out code.
- added all the changes required from memory server side.

2020-10-22 08:17 UTC, mashoodk requested changes
very minor comment.

2020-10-22 08:17 UTC, mashoodk commented on src/fam-api/fam_ops_libfabric.cpp
> +            // Save memery server address in memServerAddrs map
```suggestion
            // Save memory server address in memServerAddrs map
```

2020-10-23 05:30 UTC, faizan-barmawer commented
Pushed a commit with additional changes:
    - Added a pthread_rw_lock around FiMemsrvMap, required on server side, since memory-server is a multi-threaded application
    - Moved FiMemsrvMap from memory_registrion_libfabric.h to fam_ops_libfabric
    - Added a test case

Regards,
Faizan

2020-10-25 13:29 UTC, mashoodk approved these changes

2020-10-25 13:30 UTC, merged